config/routes.rb
Rails.application.routes.draw do
  
  root 								"static_pages#home"
  get "help" 			=> 	"static_pages#help"
  get "contact" 	=> 	"static_pages#contact"
  get "about" 		=> 	"static_pages#about"
  get "signup" 		=> 	"users#new"
  get "login"			=>	"sessions#new"
  post "login"		=>	"sessions#create"
  delete "logout"	=>	"sessions#destroy"
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: { minimum: 6,maximum: 50}  
  has_secure_password

  # Returns hash digest for a given string
  def User.digest(string)
  	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  																								BCrypt::Engine.cost
  	BCrypt::Password.create(string, cost: cost)	
  end

  # Returns a random token
  def User.new_token
  	SecureRandom.urlsafe_base64
  end

  def remember
  	self.remember_token = User.new_token
  	update_attribute(:remember_digest, User.digest(remember_token) )
  end

  # Returns true if the given token matches the digest
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
  	BCrypt::Password.new(remember_digest).is_password?(remember_token) 	
 	end 

 	def forget
 		update_attribute(:remember_digest, nil)
 	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		# Log in user
  		log_in user
  		params[:session][:remember_me] == '1'? remember(user) : forget(user)
  		redirect_to user
  	else
  		flash.now[:danger] = "Incorrect email/password combination"
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def	show
		@user = User.find( params[:id] )
	end
	
	def new
		@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		# Handle a successful save
  		log_in @user
  		remember @user
  		flash[:success] = "I want to play a game!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns a full title on per page basis
	def full_title(page_title="")
			base_title = "Mini-Twitter"
			if( page_title.empty? )
				base_title
			else
				page_title + " | #{base_title}"
			end
	end	
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Log's in the given user
	def log_in(user)
		session[:user_id] = user.id 	
	end

	def remember(user)
		user.remember
		cookies.signed[:user_id] = user.id
		cookies[:remember_token] = user.remember_token
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id) 
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id )
			if user && user.authenticated?( cookies[:remember_token] )
				log_in user
				@current_user = user
			end
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
	def	gravatar_for(user)
		gravatar_ID = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_URL = 
				"https://secure.gravatar.com/avatar/#{gravatar_ID}"
		image_tag(gravatar_URL, alt: "#{user.name}'s Image", 
							class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Mini Twitter App</a>
    by <a href="#">Burhan Nabi</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class=" navbar navbar-fixed-top navbar-inverse ">
  <div class="container">
    <%= link_to "Mini T Home", root_path, id: "logo" %> 
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>

        <% if logged_in? %>
          <li><%= link_to "Users","#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle ="dropdown">
              Account<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li><%= link_to "Log Out", logout_path, method: "delete"%></li>
            </ul>
          </li>
        <% else %>  
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </nav>   
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title( yield(:title) )%> </title>
    <%= stylesheet_link_tag    'application', media: 'all', 
        'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application',
        'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
  </head>
  
  <body>

    <%= render "layouts/header" %>
    <div class="container">

      <% flash.each do |msg_type, msg| %>
        <div class="alert alert-<%=msg_type%>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is a basic web app in which users will be able to post micro blogs, which
  will be visible to the people who follow them. Users will also be able to 
  follow other users.
</p>    

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<div class="container">
	<h1>Contact Us</h1>
	<p class="center">You can contact me at <a href="#">burhan14031@iiitd.ac.in</a> </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
    Look man! I really don't know much. If you have a problem or anything with 
    the app, just Google around. You'll probably find what you're looking for on
    Stack Overflow.
    So help page.
    <a href="#">#Random</a>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">

  <h1>Welcome to Mini - Twitter</h1>
  <p> This is the home page for the Mini Twitter app that I am trying to make.
      I,<a href="#">Burhan Nabi</a>, am making it using Rails, a Ruby framework. 
      Ruby is such a cool language.
  </p>
  <%= link_to "Sign Up Now!",signup_path, class:"btn btn-lg btn-primary" %>

</div>

<%= link_to image_tag("rails.png", alt: "Rails Logo",
    height: "5%", width:"5%"), "http://rubyonrails.org" %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h1>Sign Up</h1>

<div class="row">
  <%= form_for(@user) do |f|  %>
    <div class="col-md-6 col-md-offset-3">
      <%= render "shared/error_messages" %>

      <%= f.label :name %>
      <%= f.text_field :name , class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confiramtion, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
	 </div>
    <div class="col-md-2 col-md-offset-5">
      <%= f.submit "Create my account!", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
	<aside class="col-md-3">
		<section class="user_info">
			<h1>
				<%= gravatar_for @user %>
				<br>
				<%= @user.name %>
				<br>
				<%= @user.email %>
			</h1>
		</section>
	</aside>
</div>	